# Generated by Django 4.2.7 on 2023-11-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('descrição', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.ManyToManyField(to='blogdegames.category'),
        ),
    ]
