# Generated by Django 4.2.7 on 2023-11-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='data_postagem',
        ),
    ]
