# Generated by Django 4.2.7 on 2023-11-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0003_rename_post_date_post_data_postagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='tag_aba',
        ),
    ]
