# Generated by Django 4.2.7 on 2023-11-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0004_rename_title_tag_post_tag_aba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
    ]
