# Generated by Django 4.2.7 on 2023-11-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0006_rename_body_comment_corpo_rename_body_post_corpo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='título',
        ),
    ]
