# Generated by Django 4.2.7 on 2023-11-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0008_rename_name_comment_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.ManyToManyField(to='blogdegames.category'),
        ),
    ]
