# Generated by Django 4.2.7 on 2023-11-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0009_remove_post_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='Categorias',
        ),
    ]
