# Generated by Django 4.2.7 on 2023-11-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0010_rename_category_post_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Categorias',
            new_name='Category',
        ),
    ]
