# Generated by Django 4.2.7 on 2023-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0011_rename_categorias_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descrição',
            field=models.TextField(default='padrao'),
            preserve_default=False,
        ),
    ]
