# Generated by Django 4.2.7 on 2023-11-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdegames', '0012_category_descrição'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
